django/task_list/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),
         name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup")
]

django/task_list/task_list/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
import accounts.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
]

django/task_list/tasks/urls.py
from django.urls import path
from tasks import views as task_views

app_name = "tasks"

urlpatterns = [
    path("", task_views.TasksList.as_view(), name="all"),
    path("<int:pk>", task_views.TasksDetail.as_view(), name="single"),
    path("<username>", task_views.TasksUser.as_view(), name="user_tasks"),
    path("new/", task_views.TasksCreate.as_view(), name="create"),
    path("delete/<int:pk>", task_views.TasksDelete.as_view(), name="delete"),
]

django/task_list/accounts/models.py
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

django/task_list/tasks/models.py
from django.db import models
from django.urls import reverse
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()


class Task(models.Model):
    user = models.ForeignKey(User, related_name='tasks',
                             on_delete=models.CASCADE)
    created_date = models.DateField(auto_now=True)
    title = models.CharField(max_length=100)
    message = models.TextField()
    # message_html = models.TextField(editable=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('tasks:single', kwargs={#'username': self.user.username,
                                               'pk': self.pk})

django/task_list/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display Name"
        self.fields["email"].label = "Email Address"

django/task_list/accounts/views.py
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

django/task_list/task_list/views.py
from django.views import generic


class HomePage(generic.TemplateView):
    template_name = "index.html"


class TestPage(generic.TemplateView):
    template_name = "test.html"


class ThanksPage(generic.TemplateView):
    template_name = "thanks.html"

django/task_list/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views import generic
# Create your views here.
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib.auth import get_user_model
from django.contrib import messages
User = get_user_model()


class TasksList(LoginRequiredMixin, generic.ListView): #SelectRelatedMixin,
    model = models.Task
    #select_related = ('user', )


class TasksUser(LoginRequiredMixin, generic.ListView):
    model = models.Task
    template_name = "tasks/user_task_list.html"

    def get_queryset(self):
        try:
            self.task_user = User.objects.prefetch_related('tasks').get(
                username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.task_user.tasks.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_user'] = self.task_user
        return context


class TasksDetail(LoginRequiredMixin, generic.DetailView): #SelectRelatedMixin,
    model = models.Task
    #select_related = ("user", )
    #
    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.filter(user__username__iexact=self.kwargs.get(
    #         'username'))


class TasksCreate(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('title', 'message')
    model = models.Task

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class TasksDelete(LoginRequiredMixin, generic.DeleteView): #SelectRelatedMixin
    model = models.Task
    success_url = reverse_lazy('tasks:all')


    def get_queryset(self):
        queryset = super().get_queryset()
        #print(dir(self.request))
        #print(dir(self.model.pk))

        return queryset.filter()

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Task Deleted')
        print("asdas")
        return super().delete(*args, **kwargs)

django/task_list/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div class="container">
    <h1>Log In</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}

      <input type="submit" class="btn btn-default" value="Log In">
    </form>
  </div>
{% endblock %}

django/task_list/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
  <div class="container">
    <h1>Sign Up</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}

      <input type="submit" class="btn btn-default" value="Sign Up">
    </form>
  </div>
{% endblock %}

django/task_list/tasks/templates/tasks/_task.html
<div class="task media">
  <h3>{{task.message}}</h3>
  <div class="media-body">
    <strong>{{task.user.username}}</strong>
    <h5 class="media-heading">
      <span class="username">
        <a href="{% url 'tasks:user_tasks' username=task.user.username %}">
          @{{task.user.username}}
        </a>
      </span>

      <time class="time">
        <a href={"% url 'tasks:single' username=task.user.username pk=task.pk %}">
          {{post.created_date}}
        </a>
      </time>
    </h5>

    <div class="media-footer">
      {# <h1>{{hide_delete}}</h1> #}
      {% if hide_delete == False %}
        <a href="{% url 'tasks:delete' pk=task.pk %}" title="delete" class="btn btn-simple">
          <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
        </a>
      {% endif %}
    </div>

  </div>
</div>

django/task_list/tasks/templates/tasks/task_base.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    {% block pre_task %}{% endblock %}
    {% block task_content %}{% endblock %}
    {% block post_task %}{% endblock %}
  </div>
{% endblock %}

django/task_list/tasks/templates/tasks/task_confirm_delete.html
{% extends "tasks/task_base.html" %}

{% block task_content %}
  <h3> Are you sure you want to delete this task?</h3>
  <div class="tasks">
    {% include "tasks/_task.html" with task=object hide_delete=True %}
    <form method="task">
      {% csrf_token %}
      <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
      <a href="{% url 'tasks:single' pk=object.pk %}"
         class="btn btn-simple btn-large btn-default">Cancel</a>
    </form>
  </div>
{% endblock %}

django/task_list/tasks/templates/tasks/task_detail.html
{% extends "tasks/task_base.html" %}

django/task_list/tasks/templates/tasks/task_form.html
{% extends "tasks/task_base.html" %}
{% load bootstrap3 %}

{% block task_content %}

  <h1>Create a new Task</h1>
  <form id="taskForm" action="{% url 'tasks:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Submit">
  </form>

{% endblock %}

django/task_list/tasks/templates/tasks/task_list.html
{% extends "tasks/task_base.html" %}

{% block task_content %}
    {% if user.is_authenticated %}
      <div class="col-md-8">
        {% if task_list.count == 0 or task_list == None %}
          <h2>No created tasks yet!</h2>
        {% else %}
        <h3>Tasks:</h3>
          {% for task in task_list %}
            {% include "tasks/_task.html" with hide_delete=False %}
          {% endfor %}
        {% endif %}
      </div>

    {% endif %}
  </div>
{% endblock %}

django/task_list/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Task List</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    {# <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}"> #}

  </head>
  <body>
    <nav class="navbar mynav" role="navigation", id="navbar">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">TaskList</a>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'tasks:all' %}">Check Tasks</a></li>
            <li> <a href="{% url 'tasks:create' %}"> Create Task </a></li>
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}">Log in</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>

      </div>
    </nav>

    {% block content %}

    {% endblock %}

  </body>
</html>

django/task_list/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1>Welcome to TaskList!</h1>
    <h3>Log In or Sign Up to create your tasks.</h3>
  </div>


{% endblock %}

django/task_list/templates/test.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
</div>

{% endblock %}

django/task_list/templates/thanks.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1>Thanks for Visiting!</h1>
</div>

{% endblock %}